/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-03-03 at 20:32:41 UTC 
 * Modify at your own risk.
 */

package com.appspot.ltc_safety.admin;

/**
 * Service definition for Admin (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AdminRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Admin extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the Admin API library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ltc-safety.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "admin/v1/admin/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Admin(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Admin(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "requestConcern".
   *
   * This request holds the parameters needed by the admin server.  After setting any optional
   * parameters, call the {@link RequestConcern#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ltc_safety.admin.model.ConcernRequest}
   * @return the request
   */
  public RequestConcern requestConcern(com.appspot.ltc_safety.admin.model.ConcernRequest content) throws java.io.IOException {
    RequestConcern result = new RequestConcern(content);
    initialize(result);
    return result;
  }

  public class RequestConcern extends AdminRequest<com.appspot.ltc_safety.admin.model.Concern> {

    private static final String REST_PATH = "requestConcern";

    /**
     * Create a request for the method "requestConcern".
     *
     * This request holds the parameters needed by the the admin server.  After setting any optional
     * parameters, call the {@link RequestConcern#execute()} method to invoke the remote operation.
     * <p> {@link RequestConcern#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param content the {@link com.appspot.ltc_safety.admin.model.ConcernRequest}
     * @since 1.13
     */
    protected RequestConcern(com.appspot.ltc_safety.admin.model.ConcernRequest content) {
      super(Admin.this, "POST", REST_PATH, content, com.appspot.ltc_safety.admin.model.Concern.class);
    }

    @Override
    public RequestConcern setAlt(String alt) {
      return (RequestConcern) super.setAlt(alt);
    }

    @Override
    public RequestConcern setFields(String fields) {
      return (RequestConcern) super.setFields(fields);
    }

    @Override
    public RequestConcern setKey(String key) {
      return (RequestConcern) super.setKey(key);
    }

    @Override
    public RequestConcern setOauthToken(String oauthToken) {
      return (RequestConcern) super.setOauthToken(oauthToken);
    }

    @Override
    public RequestConcern setPrettyPrint(Boolean prettyPrint) {
      return (RequestConcern) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RequestConcern setQuotaUser(String quotaUser) {
      return (RequestConcern) super.setQuotaUser(quotaUser);
    }

    @Override
    public RequestConcern setUserIp(String userIp) {
      return (RequestConcern) super.setUserIp(userIp);
    }

    @Override
    public RequestConcern set(String parameterName, Object value) {
      return (RequestConcern) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "requestConcernList".
   *
   * This request holds the parameters needed by the admin server.  After setting any optional
   * parameters, call the {@link RequestConcernList#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ltc_safety.admin.model.ConcernListRequest}
   * @return the request
   */
  public RequestConcernList requestConcernList(com.appspot.ltc_safety.admin.model.ConcernListRequest content) throws java.io.IOException {
    RequestConcernList result = new RequestConcernList(content);
    initialize(result);
    return result;
  }

  public class RequestConcernList extends AdminRequest<com.appspot.ltc_safety.admin.model.ConcernCollection> {

    private static final String REST_PATH = "requestConcernList";

    /**
     * Create a request for the method "requestConcernList".
     *
     * This request holds the parameters needed by the the admin server.  After setting any optional
     * parameters, call the {@link RequestConcernList#execute()} method to invoke the remote
     * operation. <p> {@link RequestConcernList#initialize(com.google.api.client.googleapis.services.A
     * bstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.appspot.ltc_safety.admin.model.ConcernListRequest}
     * @since 1.13
     */
    protected RequestConcernList(com.appspot.ltc_safety.admin.model.ConcernListRequest content) {
      super(Admin.this, "POST", REST_PATH, content, com.appspot.ltc_safety.admin.model.ConcernCollection.class);
    }

    @Override
    public RequestConcernList setAlt(String alt) {
      return (RequestConcernList) super.setAlt(alt);
    }

    @Override
    public RequestConcernList setFields(String fields) {
      return (RequestConcernList) super.setFields(fields);
    }

    @Override
    public RequestConcernList setKey(String key) {
      return (RequestConcernList) super.setKey(key);
    }

    @Override
    public RequestConcernList setOauthToken(String oauthToken) {
      return (RequestConcernList) super.setOauthToken(oauthToken);
    }

    @Override
    public RequestConcernList setPrettyPrint(Boolean prettyPrint) {
      return (RequestConcernList) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RequestConcernList setQuotaUser(String quotaUser) {
      return (RequestConcernList) super.setQuotaUser(quotaUser);
    }

    @Override
    public RequestConcernList setUserIp(String userIp) {
      return (RequestConcernList) super.setUserIp(userIp);
    }

    @Override
    public RequestConcernList set(String parameterName, Object value) {
      return (RequestConcernList) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Admin}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Admin}. */
    @Override
    public Admin build() {
      return new Admin(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AdminRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAdminRequestInitializer(
        AdminRequestInitializer adminRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(adminRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
