/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-03-18 at 22:39:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.ltc_safety.admin.model;

/**
 * Model definition for Concern.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Admin API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Concern extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean archived;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ConcernData data;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean retracted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ConcernStatus> statuses;

  static {
    // hack to force ProGuard to consider ConcernStatus used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ConcernStatus.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime submissionDate;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean test;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getArchived() {
    return archived;
  }

  /**
   * @param archived archived or {@code null} for none
   */
  public Concern setArchived(java.lang.Boolean archived) {
    this.archived = archived;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public ConcernData getData() {
    return data;
  }

  /**
   * @param data data or {@code null} for none
   */
  public Concern setData(ConcernData data) {
    this.data = data;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Concern setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getRetracted() {
    return retracted;
  }

  /**
   * @param retracted retracted or {@code null} for none
   */
  public Concern setRetracted(java.lang.Boolean retracted) {
    this.retracted = retracted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<ConcernStatus> getStatuses() {
    return statuses;
  }

  /**
   * @param statuses statuses or {@code null} for none
   */
  public Concern setStatuses(java.util.List<ConcernStatus> statuses) {
    this.statuses = statuses;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getSubmissionDate() {
    return submissionDate;
  }

  /**
   * @param submissionDate submissionDate or {@code null} for none
   */
  public Concern setSubmissionDate(com.google.api.client.util.DateTime submissionDate) {
    this.submissionDate = submissionDate;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getTest() {
    return test;
  }

  /**
   * @param test test or {@code null} for none
   */
  public Concern setTest(java.lang.Boolean test) {
    this.test = test;
    return this;
  }

  @Override
  public Concern set(String fieldName, Object value) {
    return (Concern) super.set(fieldName, value);
  }

  @Override
  public Concern clone() {
    return (Concern) super.clone();
  }

}
