/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-03-18 at 22:39:45 UTC 
 * Modify at your own risk.
 */

package com.appspot.ltc_safety.admin.model;

/**
 * Model definition for ConcernListResponse.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Admin API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ConcernListResponse extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Concern> concernList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer endIndex;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer startIndex;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer totalItemsCount;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Concern> getConcernList() {
    return concernList;
  }

  /**
   * @param concernList concernList or {@code null} for none
   */
  public ConcernListResponse setConcernList(java.util.List<Concern> concernList) {
    this.concernList = concernList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEndIndex() {
    return endIndex;
  }

  /**
   * @param endIndex endIndex or {@code null} for none
   */
  public ConcernListResponse setEndIndex(java.lang.Integer endIndex) {
    this.endIndex = endIndex;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getStartIndex() {
    return startIndex;
  }

  /**
   * @param startIndex startIndex or {@code null} for none
   */
  public ConcernListResponse setStartIndex(java.lang.Integer startIndex) {
    this.startIndex = startIndex;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTotalItemsCount() {
    return totalItemsCount;
  }

  /**
   * @param totalItemsCount totalItemsCount or {@code null} for none
   */
  public ConcernListResponse setTotalItemsCount(java.lang.Integer totalItemsCount) {
    this.totalItemsCount = totalItemsCount;
    return this;
  }

  @Override
  public ConcernListResponse set(String fieldName, Object value) {
    return (ConcernListResponse) super.set(fieldName, value);
  }

  @Override
  public ConcernListResponse clone() {
    return (ConcernListResponse) super.clone();
  }

}
