// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   User API (client/v1)
// Description:
//   This is an API

#import "GTLRClientObjects.h"

// ----------------------------------------------------------------------------
//
//   GTLRClient_ConcernData
//

@implementation GTLRClient_ConcernData
@dynamic actionsTaken, concernNature, location, reporter;
@end


// ----------------------------------------------------------------------------
//
//   GTLRClient_Location
//

@implementation GTLRClient_Location
@dynamic facilityName, roomName;
@end


// ----------------------------------------------------------------------------
//
//   GTLRClient_OwnerToken
//

@implementation GTLRClient_OwnerToken
@dynamic token;
@end


// ----------------------------------------------------------------------------
//
//   GTLRClient_Reporter
//

@implementation GTLRClient_Reporter
@dynamic email, name, phoneNumber;
@end
