// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   User API (client/v1)
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRClient_Location;
@class GTLRClient_Reporter;

NS_ASSUME_NONNULL_BEGIN

/**
 *  GTLRClient_ConcernData
 */
@interface GTLRClient_ConcernData : GTLRObject

@property(nonatomic, copy, nullable) NSString *actionsTaken;
@property(nonatomic, copy, nullable) NSString *concernNature;
@property(nonatomic, strong, nullable) GTLRClient_Location *location;
@property(nonatomic, strong, nullable) GTLRClient_Reporter *reporter;

@end


/**
 *  GTLRClient_Location
 */
@interface GTLRClient_Location : GTLRObject

@property(nonatomic, copy, nullable) NSString *facilityName;
@property(nonatomic, copy, nullable) NSString *roomName;

@end


/**
 *  GTLRClient_OwnerToken
 */
@interface GTLRClient_OwnerToken : GTLRObject

@property(nonatomic, copy, nullable) NSString *token;

@end


/**
 *  GTLRClient_Reporter
 */
@interface GTLRClient_Reporter : GTLRObject

@property(nonatomic, copy, nullable) NSString *email;
@property(nonatomic, copy, nullable) NSString *name;
@property(nonatomic, copy, nullable) NSString *phoneNumber;

@end

NS_ASSUME_NONNULL_END
