/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2017-02-15 17:18:02 UTC)
 * on 2017-03-18 at 22:39:43 UTC 
 * Modify at your own risk.
 */

package com.appspot.ltc_safety.client;

/**
 * Service definition for Client (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ClientRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Client extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.22.0 of the User API library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://ltc-safety.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Client(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Client(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "fetchConcerns".
   *
   * This request holds the parameters needed by the client server.  After setting any optional
   * parameters, call the {@link FetchConcerns#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ltc_safety.client.model.OwnerTokenListWrapper}
   * @return the request
   */
  public FetchConcerns fetchConcerns(com.appspot.ltc_safety.client.model.OwnerTokenListWrapper content) throws java.io.IOException {
    FetchConcerns result = new FetchConcerns(content);
    initialize(result);
    return result;
  }

  public class FetchConcerns extends ClientRequest<com.appspot.ltc_safety.client.model.ConcernCollection> {

    private static final String REST_PATH = "concern/fetchConcerns";

    /**
     * Create a request for the method "fetchConcerns".
     *
     * This request holds the parameters needed by the the client server.  After setting any optional
     * parameters, call the {@link FetchConcerns#execute()} method to invoke the remote operation. <p>
     * {@link FetchConcerns#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param content the {@link com.appspot.ltc_safety.client.model.OwnerTokenListWrapper}
     * @since 1.13
     */
    protected FetchConcerns(com.appspot.ltc_safety.client.model.OwnerTokenListWrapper content) {
      super(Client.this, "POST", REST_PATH, content, com.appspot.ltc_safety.client.model.ConcernCollection.class);
    }

    @Override
    public FetchConcerns setAlt(java.lang.String alt) {
      return (FetchConcerns) super.setAlt(alt);
    }

    @Override
    public FetchConcerns setFields(java.lang.String fields) {
      return (FetchConcerns) super.setFields(fields);
    }

    @Override
    public FetchConcerns setKey(java.lang.String key) {
      return (FetchConcerns) super.setKey(key);
    }

    @Override
    public FetchConcerns setOauthToken(java.lang.String oauthToken) {
      return (FetchConcerns) super.setOauthToken(oauthToken);
    }

    @Override
    public FetchConcerns setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (FetchConcerns) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public FetchConcerns setQuotaUser(java.lang.String quotaUser) {
      return (FetchConcerns) super.setQuotaUser(quotaUser);
    }

    @Override
    public FetchConcerns setUserIp(java.lang.String userIp) {
      return (FetchConcerns) super.setUserIp(userIp);
    }

    @Override
    public FetchConcerns set(String parameterName, Object value) {
      return (FetchConcerns) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "retractConcern".
   *
   * This request holds the parameters needed by the client server.  After setting any optional
   * parameters, call the {@link RetractConcern#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ltc_safety.client.model.OwnerToken}
   * @return the request
   */
  public RetractConcern retractConcern(com.appspot.ltc_safety.client.model.OwnerToken content) throws java.io.IOException {
    RetractConcern result = new RetractConcern(content);
    initialize(result);
    return result;
  }

  public class RetractConcern extends ClientRequest<com.appspot.ltc_safety.client.model.UpdateConcernStatusResponse> {

    private static final String REST_PATH = "concern/retract";

    /**
     * Create a request for the method "retractConcern".
     *
     * This request holds the parameters needed by the the client server.  After setting any optional
     * parameters, call the {@link RetractConcern#execute()} method to invoke the remote operation.
     * <p> {@link RetractConcern#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param content the {@link com.appspot.ltc_safety.client.model.OwnerToken}
     * @since 1.13
     */
    protected RetractConcern(com.appspot.ltc_safety.client.model.OwnerToken content) {
      super(Client.this, "POST", REST_PATH, content, com.appspot.ltc_safety.client.model.UpdateConcernStatusResponse.class);
    }

    @Override
    public RetractConcern setAlt(java.lang.String alt) {
      return (RetractConcern) super.setAlt(alt);
    }

    @Override
    public RetractConcern setFields(java.lang.String fields) {
      return (RetractConcern) super.setFields(fields);
    }

    @Override
    public RetractConcern setKey(java.lang.String key) {
      return (RetractConcern) super.setKey(key);
    }

    @Override
    public RetractConcern setOauthToken(java.lang.String oauthToken) {
      return (RetractConcern) super.setOauthToken(oauthToken);
    }

    @Override
    public RetractConcern setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RetractConcern) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RetractConcern setQuotaUser(java.lang.String quotaUser) {
      return (RetractConcern) super.setQuotaUser(quotaUser);
    }

    @Override
    public RetractConcern setUserIp(java.lang.String userIp) {
      return (RetractConcern) super.setUserIp(userIp);
    }

    @Override
    public RetractConcern set(String parameterName, Object value) {
      return (RetractConcern) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "submitConcern".
   *
   * This request holds the parameters needed by the client server.  After setting any optional
   * parameters, call the {@link SubmitConcern#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.appspot.ltc_safety.client.model.ConcernData}
   * @return the request
   */
  public SubmitConcern submitConcern(com.appspot.ltc_safety.client.model.ConcernData content) throws java.io.IOException {
    SubmitConcern result = new SubmitConcern(content);
    initialize(result);
    return result;
  }

  public class SubmitConcern extends ClientRequest<com.appspot.ltc_safety.client.model.SubmitConcernResponse> {

    private static final String REST_PATH = "concern/submit";

    /**
     * Create a request for the method "submitConcern".
     *
     * This request holds the parameters needed by the the client server.  After setting any optional
     * parameters, call the {@link SubmitConcern#execute()} method to invoke the remote operation. <p>
     * {@link SubmitConcern#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param content the {@link com.appspot.ltc_safety.client.model.ConcernData}
     * @since 1.13
     */
    protected SubmitConcern(com.appspot.ltc_safety.client.model.ConcernData content) {
      super(Client.this, "POST", REST_PATH, content, com.appspot.ltc_safety.client.model.SubmitConcernResponse.class);
    }

    @Override
    public SubmitConcern setAlt(java.lang.String alt) {
      return (SubmitConcern) super.setAlt(alt);
    }

    @Override
    public SubmitConcern setFields(java.lang.String fields) {
      return (SubmitConcern) super.setFields(fields);
    }

    @Override
    public SubmitConcern setKey(java.lang.String key) {
      return (SubmitConcern) super.setKey(key);
    }

    @Override
    public SubmitConcern setOauthToken(java.lang.String oauthToken) {
      return (SubmitConcern) super.setOauthToken(oauthToken);
    }

    @Override
    public SubmitConcern setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SubmitConcern) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SubmitConcern setQuotaUser(java.lang.String quotaUser) {
      return (SubmitConcern) super.setQuotaUser(quotaUser);
    }

    @Override
    public SubmitConcern setUserIp(java.lang.String userIp) {
      return (SubmitConcern) super.setUserIp(userIp);
    }

    @Override
    public SubmitConcern set(String parameterName, Object value) {
      return (SubmitConcern) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "submitTestConcern".
   *
   * This request holds the parameters needed by the client server.  After setting any optional
   * parameters, call the {@link SubmitTestConcern#execute()} method to invoke the remote operation.
   *
   * @param isTest
   * @param content the {@link com.appspot.ltc_safety.client.model.ConcernData}
   * @return the request
   */
  public SubmitTestConcern submitTestConcern(java.lang.Boolean isTest, com.appspot.ltc_safety.client.model.ConcernData content) throws java.io.IOException {
    SubmitTestConcern result = new SubmitTestConcern(isTest, content);
    initialize(result);
    return result;
  }

  public class SubmitTestConcern extends ClientRequest<com.appspot.ltc_safety.client.model.SubmitConcernResponse> {

    private static final String REST_PATH = "test/concern/submit";

    /**
     * Create a request for the method "submitTestConcern".
     *
     * This request holds the parameters needed by the the client server.  After setting any optional
     * parameters, call the {@link SubmitTestConcern#execute()} method to invoke the remote operation.
     * <p> {@link SubmitTestConcern#initialize(com.google.api.client.googleapis.services.AbstractGoogl
     * eClientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param isTest
     * @param content the {@link com.appspot.ltc_safety.client.model.ConcernData}
     * @since 1.13
     */
    protected SubmitTestConcern(java.lang.Boolean isTest, com.appspot.ltc_safety.client.model.ConcernData content) {
      super(Client.this, "POST", REST_PATH, content, com.appspot.ltc_safety.client.model.SubmitConcernResponse.class);
      this.isTest = com.google.api.client.util.Preconditions.checkNotNull(isTest, "Required parameter isTest must be specified.");
    }

    @Override
    public SubmitTestConcern setAlt(java.lang.String alt) {
      return (SubmitTestConcern) super.setAlt(alt);
    }

    @Override
    public SubmitTestConcern setFields(java.lang.String fields) {
      return (SubmitTestConcern) super.setFields(fields);
    }

    @Override
    public SubmitTestConcern setKey(java.lang.String key) {
      return (SubmitTestConcern) super.setKey(key);
    }

    @Override
    public SubmitTestConcern setOauthToken(java.lang.String oauthToken) {
      return (SubmitTestConcern) super.setOauthToken(oauthToken);
    }

    @Override
    public SubmitTestConcern setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SubmitTestConcern) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SubmitTestConcern setQuotaUser(java.lang.String quotaUser) {
      return (SubmitTestConcern) super.setQuotaUser(quotaUser);
    }

    @Override
    public SubmitTestConcern setUserIp(java.lang.String userIp) {
      return (SubmitTestConcern) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Boolean isTest;

    /**

     */
    public java.lang.Boolean getIsTest() {
      return isTest;
    }

    public SubmitTestConcern setIsTest(java.lang.Boolean isTest) {
      this.isTest = isTest;
      return this;
    }

    @Override
    public SubmitTestConcern set(String parameterName, Object value) {
      return (SubmitTestConcern) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Client}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Client}. */
    @Override
    public Client build() {
      return new Client(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ClientRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setClientRequestInitializer(
        ClientRequestInitializer clientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(clientRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
