// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   User API (client/v1)
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRObject.h"
#else
  #import "GTLRObject.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRClient_Concern;
@class GTLRClient_ConcernData;
@class GTLRClient_ConcernStatus;
@class GTLRClient_Location;
@class GTLRClient_OwnerToken;
@class GTLRClient_Reporter;

NS_ASSUME_NONNULL_BEGIN

// ----------------------------------------------------------------------------
// Constants - For some of the classes' properties below.

// ----------------------------------------------------------------------------
// GTLRClient.ConcernStatusType

/** Value: "PENDING" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Pending;
/** Value: "RESOLVED" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Resolved;
/** Value: "RESPONDING24" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Responding24;
/** Value: "RESPONDING48" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Responding48;
/** Value: "RESPONDING72" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Responding72;
/** Value: "RETRACTED" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Retracted;
/** Value: "SEEN" */
GTLR_EXTERN NSString * const kGTLRClient_ConcernStatusType_Seen;

/**
 *  GTLRClient_Concern
 */
@interface GTLRClient_Concern : GTLRObject

/**
 *  archived
 *
 *  Uses NSNumber of boolValue.
 */
@property(nonatomic, strong, nullable) NSNumber *archived;

@property(nonatomic, strong, nullable) GTLRClient_ConcernData *data;

/**
 *  identifier
 *
 *  identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
 *
 *  Uses NSNumber of longLongValue.
 */
@property(nonatomic, strong, nullable) NSNumber *identifier;

@property(nonatomic, strong, nullable) NSArray<GTLRClient_ConcernStatus *> *statuses;
@property(nonatomic, strong, nullable) GTLRDateTime *submissionDate;

@end


/**
 *  GTLRClient_ConcernData
 */
@interface GTLRClient_ConcernData : GTLRObject

@property(nonatomic, copy, nullable) NSString *actionsTaken;
@property(nonatomic, copy, nullable) NSString *concernNature;
@property(nonatomic, strong, nullable) GTLRClient_Location *location;
@property(nonatomic, strong, nullable) GTLRClient_Reporter *reporter;

@end


/**
 *  GTLRClient_ConcernStatus
 */
@interface GTLRClient_ConcernStatus : GTLRObject

@property(nonatomic, strong, nullable) GTLRDateTime *creationDate;
@property(nonatomic, copy, nullable) NSString *type;

@end


/**
 *  GTLRClient_Location
 */
@interface GTLRClient_Location : GTLRObject

@property(nonatomic, copy, nullable) NSString *facilityName;
@property(nonatomic, copy, nullable) NSString *roomName;

@end


/**
 *  GTLRClient_OwnerToken
 */
@interface GTLRClient_OwnerToken : GTLRObject

@property(nonatomic, copy, nullable) NSString *token;

@end


/**
 *  GTLRClient_Reporter
 */
@interface GTLRClient_Reporter : GTLRObject

@property(nonatomic, copy, nullable) NSString *email;
@property(nonatomic, copy, nullable) NSString *name;
@property(nonatomic, copy, nullable) NSString *phoneNumber;

@end


/**
 *  GTLRClient_SubmitConcernResponse
 */
@interface GTLRClient_SubmitConcernResponse : GTLRObject

@property(nonatomic, strong, nullable) GTLRClient_Concern *concern;
@property(nonatomic, strong, nullable) GTLRClient_OwnerToken *ownerToken;

@end

NS_ASSUME_NONNULL_END
