// NOTE: This file was generated by the ServiceGenerator.

// ----------------------------------------------------------------------------
// API:
//   User API (client/v1)
// Description:
//   This is an API

#if GTLR_BUILT_AS_FRAMEWORK
  #import "GTLR/GTLRQuery.h"
#else
  #import "GTLRQuery.h"
#endif

#if GTLR_RUNTIME_VERSION != 3000
#error This file was generated by a different version of ServiceGenerator which is incompatible with this GTLR library source.
#endif

@class GTLRClient_ConcernData;
@class GTLRClient_OwnerToken;
@class GTLRClient_OwnerTokenListWrapper;

NS_ASSUME_NONNULL_BEGIN

/**
 *  Parent class for other Client query classes.
 */
@interface GTLRClientQuery : GTLRQuery

/** Selector specifying which fields to include in a partial response. */
@property(nonatomic, copy, nullable) NSString *fields;

@end

/**
 *  GTLRClientQuery_FetchConcerns
 *
 *  Method: client.fetchConcerns
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeClientUserinfoEmail
 */
@interface GTLRClientQuery_FetchConcerns : GTLRClientQuery
// Previous library name was
//   +[GTLQueryClient queryForFetchConcernsWithObject:]

/**
 *  Fetches a @c GTLRClient_ConcernCollection.
 *
 *  @param object The @c GTLRClient_OwnerTokenListWrapper to include in the
 *    query.
 *
 *  @returns GTLRClientQuery_FetchConcerns
 */
+ (instancetype)queryWithObject:(GTLRClient_OwnerTokenListWrapper *)object;

@end

/**
 *  GTLRClientQuery_RetractConcern
 *
 *  Method: client.retractConcern
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeClientUserinfoEmail
 */
@interface GTLRClientQuery_RetractConcern : GTLRClientQuery
// Previous library name was
//   +[GTLQueryClient queryForRetractConcernWithObject:]

/**
 *  Fetches a @c GTLRClient_UpdateConcernStatusResponse.
 *
 *  @param object The @c GTLRClient_OwnerToken to include in the query.
 *
 *  @returns GTLRClientQuery_RetractConcern
 */
+ (instancetype)queryWithObject:(GTLRClient_OwnerToken *)object;

@end

/**
 *  GTLRClientQuery_SubmitConcern
 *
 *  Method: client.submitConcern
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeClientUserinfoEmail
 */
@interface GTLRClientQuery_SubmitConcern : GTLRClientQuery
// Previous library name was
//   +[GTLQueryClient queryForSubmitConcernWithObject:]

/**
 *  Fetches a @c GTLRClient_SubmitConcernResponse.
 *
 *  @param object The @c GTLRClient_ConcernData to include in the query.
 *
 *  @returns GTLRClientQuery_SubmitConcern
 */
+ (instancetype)queryWithObject:(GTLRClient_ConcernData *)object;

@end

/**
 *  GTLRClientQuery_SubmitTestConcern
 *
 *  Method: client.submitTestConcern
 *
 *  Authorization scope(s):
 *    @c kGTLRAuthScopeClientUserinfoEmail
 */
@interface GTLRClientQuery_SubmitTestConcern : GTLRClientQuery
// Previous library name was
//   +[GTLQueryClient queryForSubmitTestConcernWithObject:isTest:]

@property(nonatomic, assign) BOOL isTest;

/**
 *  Fetches a @c GTLRClient_SubmitConcernResponse.
 *
 *  @param object The @c GTLRClient_ConcernData to include in the query.
 *  @param isTest BOOL
 *
 *  @returns GTLRClientQuery_SubmitTestConcern
 */
+ (instancetype)queryWithObject:(GTLRClient_ConcernData *)object
                         isTest:(BOOL)isTest;

@end

NS_ASSUME_NONNULL_END
